<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Carrito_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get carrito by id
     */
    function get_carrito($id)
    {
        return $this->db->get_where('carrito',array('id_mesa'=>$id))->row_array();
    }
        
    /*
     * Get all carritos
     */
    function get_all_carritos()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('carrito')->result_array();
    }
        
    /*
     * function to add new carrito
     */
    function add_carrito($params)
    {
        $this->db->insert('carrito',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update carrito
     */
    function update_carrito($id,$params)
    {
        $this->db->where('id_mesa',$id);
        return $this->db->update('carrito',$params);
    }
    
    /*
     * function to delete carrito
     */
    function delete_carrito($id)
    {
        return $this->db->delete('carrito',array('id_mesa'=>$id));
    }
}
