<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cliente_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get cliente by id
     */
    function get_cliente($id)
    {
        return $this->db->get_where('clientes',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all clientes
     */
    function get_all_clientes()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('clientes')->result_array();
    }
        
    /*
     * function to add new cliente
     */
    function add_cliente($params)
    {
        $this->db->insert('clientes',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update cliente
     */
    function update_cliente($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('clientes',$params);
    }
    
    /*
     * function to delete cliente
     */
    function delete_cliente($id)
    {
        return $this->db->delete('clientes',array('id'=>$id));
    }
}
