<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cocina_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    function agregaOrden($params){
        $this->db->insert('cocina',$params);
    }

    /**
     * 1 - RECIBIDO
     * 2 - PREPARANDO
     * 3 - LISTO
     * 4 - ENTREGADO
     * 5 o SUPERIOR - NO SE MUESTRA EN LISTA
     */
    function getOrdenes(){
        $this->db->order_by('id', 'desc');
        return $this->db->get('cocina')->result_array();
    }
    function updateStatus($id){
        $status = $this->db->get_where('cocina',array('id'=>$id))->row_array();
        $num = $status['status'];
        $num = $num+1;
        $this->db->where('id',$id);
        $this->db->update('cocina',array('status'=>$num));
    }
    /**
     * 1 - RECIBIDO
     * 2 - PREPARANDO
     * 3 - LISTO
     * 4 - ENTREGADO
     * 5 o SUPERIOR - NO SE MUESTRA EN LISTA
     * FUNCION ALERTA PEDIDO LISTO STATUS = 3
     */
    function getOrdenesListas(){
        $this->db->order_by('id', 'desc');
        $this->db->where('status',3);
        return $this->db->get('cocina')->result_array();
    }



















}