<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Detalle_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get detalle by id
     */
    function get_detalle($id)
    {
        return $this->db->get_where('detalles',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all detalles
     */
    function get_all_detalles()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('detalles')->result_array();
    }
        
    /*
     * function to add new detalle
     */
    function add_detalle($params)
    {
        $this->db->insert('detalles',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update detalle
     */
    function update_detalle($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('detalles',$params);
    }
    
    /*
     * function to delete detalle
     */
    function delete_detalle($id)
    {
        return $this->db->delete('detalles',array('id'=>$id));
    }
}
