<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Entrada_efectivo_caja_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function getCaja($fecha){
        //$this->db->select('importe');
        $this->db->like('fecha', $fecha);
        $query = $this->db->get('saldo_inicial_caja');
        return $query->row_array();
    }
    
    /*
     * Get entrada_efectivo_caja by id
     */
    function get_entrada_efectivo_caja($id)
    {
        return $this->db->get_where('saldo_inicial_caja',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all entrada_efectivo_caja
     */
    function get_all_entrada_efectivo_caja()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('saldo_inicial_caja')->result_array();
    }
        
    /*
     * function to add new entrada_efectivo_caja
     */
    function add_entrada_efectivo_caja($params)
    {
        $this->db->insert('saldo_inicial_caja',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update entrada_efectivo_caja
     */
    function update_entrada_efectivo_caja($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('saldo_inicial_caja',$params);
    }
    
    /*
     * function to delete entrada_efectivo_caja
     */
    function delete_entrada_efectivo_caja($id)
    {
        return $this->db->delete('saldo_inicial_caja',array('id'=>$id));
    }

    /*
     * Get fecha inicio entrada caja
     */
    function get_inicio_entrada_efectivo_caja()
    {
        $this->db->select('fecha');
        $this->db->order_by('id', 'asc');
        $this->db->limit('1');
        return $this->db->get('saldo_inicial_caja')->result_array();
    }
}
