<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Historial_ventas_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function get_all($fecha = ""){
        if ($fecha == "") {
            date_default_timezone_set('America/Mexico_City');
            $fecha = date('Y-m-d');
        }
        $sql="SELECT ventas.id as folio, fecha,
                SUM(detalles.cantidad) AS cantidad,
                SUM(detalles.importe) AS total 
                FROM detalles 
                JOIN ventas
                ON ventas.id = detalles.id_venta
                WHERE ventas.fecha
                LIKE '%".date('Y-m-d', strtotime($fecha))."%'
                GROUP BY folio";                
        $query = $this->db->query($sql);
        return $query->result_array();
    }





}//end class