<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Mesa_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    function rename_mesa($params,$id){
        $this->db->where('id',$id);
        return $this->db->update('mesas',$params);
    }
    
    /*
     * Get mesa by id
     */
    function get_mesa($id)
    {
        return $this->db->get_where('mesas',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all mesas
     */
    function get_all_mesas()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('mesas')->result_array();
    }
        
    /*
     * function to add new mesa
     */
    function add_mesa($params)
    {
        $this->db->insert('mesas',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update mesa
     */
    function update_mesa($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('mesas',$params);
    }
    
    /*
     * function to delete mesa
     */
    function delete_mesa($id)
    {
        return $this->db->delete('mesas',array('id'=>$id));
    }

    /**
     * DEVUELVE LISTADO MESAS OCUPADAS CON PEDIDOS
     */
    function get_mesa_ocupada(){        
        return $this->db->get('carrito')->result_array();
    }
}
