<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Metodos_pago_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get metodos_pago by id
     */
    function get_metodos_pago($id)
    {
        return $this->db->get_where('metodos_pago',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all metodos_pago
     */
    function get_all_metodos_pago()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('metodos_pago')->result_array();
    }
        
    /*
     * function to add new metodos_pago
     */
    function add_metodos_pago($params)
    {
        $this->db->insert('metodos_pago',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update metodos_pago
     */
    function update_metodos_pago($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('metodos_pago',$params);
    }
    
    /*
     * function to delete metodos_pago
     */
    function delete_metodos_pago($id)
    {
        return $this->db->delete('metodos_pago',array('id'=>$id));
    }
}
